
#RECUERDA QUE HAS PUESTO LA BBDD DENOMINADA crudcurso
# Esta era la de MYSQL --> jdbc:mysql://localhost:3306/crudcurso?useSSL=false&serverTimezone=UTC&useLegacyDateTimeCode=false
# Esta era la de Heroku --> postgres://jeryhazkhwtegt:1f921054502d7c2968dd03a63752acbe4e3315a90761a791e524678297c5066e@ec2-54-74-35-87.eu-west-1.compute.amazonaws.com:5432/ddk4u4pe9r2ecf

spring.datasource.url = postgres://jeryhazkhwtegt:1f921054502d7c2968dd03a63752acbe4e3315a90761a791e524678297c5066e@ec2-54-74-35-87.eu-west-1.compute.amazonaws.com:5432/ddk4u4pe9r2ecf




# nombre de usuario y contraseña

spring.datasource.username = jeryhazkhwtegt

spring.datasource.password = 1f921054502d7c2968dd03a63752acbe4e3315a90761a791e524678297c5066e


# mostrar sentencias SQL en la consola
spring.jpa.show-sql = true

# actualizar base de datos y crear entidades
spring.jpa.hibernate.ddl-auto = update

# hibernate genera SQL optimizado
# La de MYSQL era --> org.hibernate.dialect.MySQL5Dialect
# LA DE POSTGRESQL DE HEROKU ERA -->  org.hibernate.dialect.PostgreSQL10Dialect
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQL10Dialect

# security          - Esta variable utilizaremos para la firma de seguridad, tiempo de expiración, 10 horas
jwt.secret = secret
jwt.expiration = 36000

