
#RECUERDA QUE HAS PUESTO LA BBDD DENOMINADA crudcurso
# Esta era la de MYSQL --> jdbc:mysql://localhost:3306/crudcurso?useSSL=false&serverTimezone=UTC&useLegacyDateTimeCode=false
# Esta era la de Heroku --> postgres://cmeeynlpyoobxo:a2e0d1072cf0f507daec3eda05a6ea24b3742cad375b423c3060711922b8d4ce@ec2-52-17-53-249.eu-west-1.compute.amazonaws.com:5432/dabapac3kqadr5

spring.datasource.url = jdbc:mysql://localhost:3306/crudcurso?useSSL=false&serverTimezone=UTC&useLegacyDateTimeCode=false



# nombre de usuario y contrase�a            el usuario era --> root
# usuario de heroku --> cmeeynlpyoobxo

spring.datasource.username = root

# la contrase�a era --> root
# contrase�a de heroku --> a2e0d1072cf0f507daec3eda05a6ea24b3742cad375b423c3060711922b8d4ce

spring.datasource.password = root


# mostrar sentencias SQL en la consola
spring.jpa.show-sql = true

# actualizar base de datos y crear entidades
spring.jpa.hibernate.ddl-auto = update

# hibernate genera SQL optimizado
# La de MYSQL era --> org.hibernate.dialect.MySQL5Dialect
# LA DE POSTGRESQL DE HEROKU ERA -->  org.hibernate.dialect.PostgreSQL10Dialect
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect

# security          - Esta variable utilizaremos para la firma de seguridad, tiempo de expiraci�n, 10 horas
jwt.secret = secret
jwt.expiration = 36000

